spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
#        - id: HEALTH-CHECK
#          uri: lb://SHAN-GATEWAY # madatory지만 filter에서 완료되기 때문에 의미 없음.
#          predicates:
#            - Path=/healthcheck
#          filters:
#            - name: HealthCheck

        - id: FRONT_ROOT
          uri: lb://SHAN-FRONT
          predicates:
            - Path=/
          filters:
            - name: Logger

        - id: OAUTH-SERVICE
          uri: lb://SHAN-AUTH
          predicates:
            - Path=/oauth2/authorization/**
          filters:
            - name: Logger

        - id: POST-OAUTH-SERVICE
          uri: lb://SHAN-AUTH
          predicates:
            - Path=/login/oauth2/code/**
          filters:
            - name: Logger

        - id: LOGIN-SERVICE
          uri: lb://SHAN-AUTH
          predicates:
            - Path=/api/auth/login
          filters:
            - name: Logger

        - id: AUTH-SERVICE
          uri: lb://SHAN-AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - name: Logger
            - name: JwtAuth
              args:
                roles: ROLE_USER

        - id: PUBLIC-USER-SERVICE
          uri: lb://SHAN-USER
          predicates:
            - Path=/api/public/user/**
          filters:
            - name: Logger
            - name: RefererCheck
              args:
                referers:
                  - http://localhost:8081
                  - http://lifrary.ga:9001

        - id: FRONT-HANDLER
          uri: lb://SHAN-FRONT
          predicates:
            - Path=/**

gateway:
  filter:
    jwt-auth:
      cookie-name: jwt
      secret-key: De6r!tW*t8eiifxm6d#nh_af69eijfv40ru*h-r!ewijfsajif8ewjh9dw3m5dwk # authservice가 제공하는 key값과 같아야 한다.
      header-name: X-Auth
      jwt-claims: sub, name, email, profileImage

server:
  port: 9001
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-alias: iotree
    key-store-password: Iotree0401

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
